<?php require 'config.php'; requiereModulo('candidatos');
$edit=null; $mensaje='';
if(isset($_GET['eliminar'])){try{$pdo->prepare('DELETE FROM candidatos WHERE id_candidato=?')->execute([(int)$_GET['eliminar']]);header('Location: candidatos.php?ok=eliminado');exit;}catch(PDOException $e){$mensaje='No se puede eliminar el candidato porque tiene resultados asociados.';}}
if(isset($_GET['editar'])){$st=$pdo->prepare('SELECT * FROM candidatos WHERE id_candidato=?');$st->execute([(int)$_GET['editar']]);$edit=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id_candidato']??0); if($id){$st=$pdo->prepare('UPDATE candidatos SET nombre=?, partido=?, cargo=?, id_votacion=?, estado=? WHERE id_candidato=?');$st->execute([$_POST['nombre'],$_POST['partido'],$_POST['cargo'],$_POST['id_votacion'],$_POST['estado'],$id]);}else{$st=$pdo->prepare('INSERT INTO candidatos(nombre,partido,cargo,id_votacion,estado) VALUES(?,?,?,?,?)');$st->execute([$_POST['nombre'],$_POST['partido'],$_POST['cargo'],$_POST['id_votacion'],$_POST['estado']]);} header('Location: candidatos.php?ok=guardado');exit;}
require 'header.php'; $votaciones=$pdo->query('SELECT * FROM votaciones ORDER BY nombre')->fetchAll(); $rows=$pdo->query('SELECT c.*, v.nombre votacion FROM candidatos c JOIN votaciones v ON c.id_votacion=v.id_votacion ORDER BY c.id_candidato DESC')->fetchAll(); ?>
<h1>Candidatos</h1><?php if($mensaje): ?><div class="alert error"><?=e($mensaje)?></div><?php endif; ?><?php if(isset($_GET['ok'])): ?><div class="alert success">Operación realizada correctamente.</div><?php endif; ?>
<form method="POST" class="form-grid"><input type="hidden" name="id_candidato" value="<?=e($edit['id_candidato']??'')?>"><input name="nombre" placeholder="Nombre del candidato" value="<?=e($edit['nombre']??'')?>" required><input name="partido" placeholder="Partido / planilla" value="<?=e($edit['partido']??'')?>" required><input name="cargo" placeholder="Cargo" value="<?=e($edit['cargo']??'Presidente')?>" required><select name="id_votacion"><?php foreach($votaciones as $v): ?><option value="<?=e($v['id_votacion'])?>" <?=($edit['id_votacion']??'')==$v['id_votacion']?'selected':''?>><?=e($v['nombre'])?></option><?php endforeach; ?></select><select name="estado"><?php foreach(['Activo','Inactivo'] as $op): ?><option <?=($edit['estado']??'Activo')==$op?'selected':''?>><?=$op?></option><?php endforeach; ?></select><button><?= $edit?'Actualizar':'Guardar' ?> candidato</button><?php if($edit): ?><a class="btn secondary" href="candidatos.php">Cancelar</a><?php endif; ?></form>
<table><tr><th>ID</th><th>Nombre</th><th>Partido</th><th>Cargo</th><th>Votación</th><th>Estado</th><th>Acciones</th></tr><?php foreach($rows as $r): ?><tr><td><?=e($r['id_candidato'])?></td><td><?=e($r['nombre'])?></td><td><?=e($r['partido'])?></td><td><?=e($r['cargo'])?></td><td><?=e($r['votacion'])?></td><td><span class="badge"><?=e($r['estado'])?></span></td><td class="actions"><a class="btn small" href="candidatos.php?editar=<?=e($r['id_candidato'])?>">Editar</a><a class="btn small danger" onclick="return confirm('¿Eliminar candidato?')" href="candidatos.php?eliminar=<?=e($r['id_candidato'])?>">Eliminar</a></td></tr><?php endforeach; ?></table>
<?php require 'footer.php'; ?>
