<?php require 'config.php'; requiereModulo('mesas');
$edit=null; $mensaje='';
if(isset($_GET['eliminar'])){try{$pdo->prepare('DELETE FROM mesas WHERE id_mesa=?')->execute([(int)$_GET['eliminar']]);header('Location: mesas.php?ok=eliminado');exit;}catch(PDOException $e){$mensaje='No se puede eliminar la mesa porque tiene resultados asociados.';}}
if(isset($_GET['editar'])){$st=$pdo->prepare('SELECT * FROM mesas WHERE id_mesa=?');$st->execute([(int)$_GET['editar']]);$edit=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id_mesa']??0); if($id){$st=$pdo->prepare('UPDATE mesas SET numero_mesa=?, centro_votacion=?, municipio=?, departamento=?, estado=? WHERE id_mesa=?');$st->execute([$_POST['numero_mesa'],$_POST['centro_votacion'],$_POST['municipio'],$_POST['departamento'],$_POST['estado'],$id]);}else{$st=$pdo->prepare('INSERT INTO mesas(numero_mesa,centro_votacion,municipio,departamento,estado) VALUES(?,?,?,?,?)');$st->execute([$_POST['numero_mesa'],$_POST['centro_votacion'],$_POST['municipio'],$_POST['departamento'],$_POST['estado']]);} header('Location: mesas.php?ok=guardado');exit;}
require 'header.php'; $rows=$pdo->query('SELECT * FROM mesas ORDER BY id_mesa DESC')->fetchAll(); ?>
<h1>Mesas electorales</h1><?php if($mensaje): ?><div class="alert error"><?=e($mensaje)?></div><?php endif; ?><?php if(isset($_GET['ok'])): ?><div class="alert success">Operación realizada correctamente.</div><?php endif; ?>
<form method="POST" class="form-grid"><input type="hidden" name="id_mesa" value="<?=e($edit['id_mesa']??'')?>"><input name="numero_mesa" placeholder="Número de mesa" value="<?=e($edit['numero_mesa']??'')?>" required><input name="centro_votacion" placeholder="Centro de votación" value="<?=e($edit['centro_votacion']??'')?>" required><input name="municipio" placeholder="Municipio" value="<?=e($edit['municipio']??'')?>" required><input name="departamento" placeholder="Departamento" value="<?=e($edit['departamento']??'Guatemala')?>" required><select name="estado"><?php foreach(['Abierta','Cerrada','En revisión'] as $op): ?><option <?=($edit['estado']??'Abierta')==$op?'selected':''?>><?=$op?></option><?php endforeach; ?></select><button><?= $edit?'Actualizar':'Guardar' ?> mesa</button><?php if($edit): ?><a class="btn secondary" href="mesas.php">Cancelar</a><?php endif; ?></form>
<table><tr><th>ID</th><th>Mesa</th><th>Centro</th><th>Municipio</th><th>Departamento</th><th>Estado</th><th>Acciones</th></tr><?php foreach($rows as $r): ?><tr><td><?=e($r['id_mesa'])?></td><td><?=e($r['numero_mesa'])?></td><td><?=e($r['centro_votacion'])?></td><td><?=e($r['municipio'])?></td><td><?=e($r['departamento'])?></td><td><span class="badge"><?=e($r['estado'])?></span></td><td class="actions"><a class="btn small" href="mesas.php?editar=<?=e($r['id_mesa'])?>">Editar</a><a class="btn small danger" onclick="return confirm('¿Eliminar mesa?')" href="mesas.php?eliminar=<?=e($r['id_mesa'])?>">Eliminar</a></td></tr><?php endforeach; ?></table>
<?php require 'footer.php'; ?>
