<?php require 'config.php'; requiereModulo('resultados');
$edit=null; $mensaje='';
if(isset($_GET['eliminar'])){$pdo->prepare('DELETE FROM resultados WHERE id_resultado=?')->execute([(int)$_GET['eliminar']]);header('Location: resultados.php?ok=eliminado');exit;}
if(isset($_GET['editar'])){$st=$pdo->prepare('SELECT * FROM resultados WHERE id_resultado=?');$st->execute([(int)$_GET['editar']]);$edit=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $id=(int)($_POST['id_resultado']??0);
 $st=$pdo->prepare('SELECT COUNT(*) FROM resultados WHERE id_votacion=? AND id_mesa=? AND id_candidato=? AND id_resultado<>?');$st->execute([$_POST['id_votacion'],$_POST['id_mesa'],$_POST['id_candidato'],$id]);
 if($st->fetchColumn()>0){$mensaje='Ya existe un resultado para esa votación, mesa y candidato. Edita el existente.';} else {
  if($id){$st=$pdo->prepare('UPDATE resultados SET id_votacion=?, id_mesa=?, id_candidato=?, votos=?, observaciones=?, id_usuario=? WHERE id_resultado=?');$st->execute([$_POST['id_votacion'],$_POST['id_mesa'],$_POST['id_candidato'],$_POST['votos'],$_POST['observaciones'],$_SESSION['id_usuario'],$id]);}
  else{$st=$pdo->prepare('INSERT INTO resultados(id_votacion,id_mesa,id_candidato,votos,observaciones,id_usuario) VALUES(?,?,?,?,?,?)');$st->execute([$_POST['id_votacion'],$_POST['id_mesa'],$_POST['id_candidato'],$_POST['votos'],$_POST['observaciones'],$_SESSION['id_usuario']]);}
  header('Location: resultados.php?ok=guardado');exit;
 }
}
require 'header.php';
$votaciones=$pdo->query('SELECT * FROM votaciones ORDER BY nombre')->fetchAll(); $mesas=$pdo->query('SELECT * FROM mesas ORDER BY numero_mesa')->fetchAll(); $candidatos=$pdo->query('SELECT * FROM candidatos WHERE estado="Activo" ORDER BY nombre')->fetchAll();
$rows=$pdo->query('SELECT r.*, v.nombre votacion, m.numero_mesa, m.centro_votacion, c.nombre candidato, c.partido, u.nombre usuario FROM resultados r JOIN votaciones v ON r.id_votacion=v.id_votacion JOIN mesas m ON r.id_mesa=m.id_mesa JOIN candidatos c ON r.id_candidato=c.id_candidato LEFT JOIN usuarios u ON r.id_usuario=u.id_usuario ORDER BY r.id_resultado DESC')->fetchAll(); ?>
<h1>Registro de resultados</h1><?php if($mensaje): ?><div class="alert error"><?=e($mensaje)?></div><?php endif; ?><?php if(isset($_GET['ok'])): ?><div class="alert success">Operación realizada correctamente.</div><?php endif; ?>
<form method="POST" class="form-grid"><input type="hidden" name="id_resultado" value="<?=e($edit['id_resultado']??'')?>"><select name="id_votacion"><?php foreach($votaciones as $v): ?><option value="<?=e($v['id_votacion'])?>" <?=($edit['id_votacion']??'')==$v['id_votacion']?'selected':''?>><?=e($v['nombre'])?></option><?php endforeach; ?></select><select name="id_mesa"><?php foreach($mesas as $m): ?><option value="<?=e($m['id_mesa'])?>" <?=($edit['id_mesa']??'')==$m['id_mesa']?'selected':''?>>Mesa <?=e($m['numero_mesa'])?> - <?=e($m['centro_votacion'])?></option><?php endforeach; ?></select><select name="id_candidato"><?php foreach($candidatos as $c): ?><option value="<?=e($c['id_candidato'])?>" <?=($edit['id_candidato']??'')==$c['id_candidato']?'selected':''?>><?=e($c['nombre'])?> / <?=e($c['partido'])?></option><?php endforeach; ?></select><input type="number" min="0" name="votos" placeholder="Cantidad de votos" value="<?=e($edit['votos']??'')?>" required><input name="observaciones" placeholder="Observaciones" value="<?=e($edit['observaciones']??'')?>"><button><?= $edit?'Actualizar':'Guardar' ?> resultado</button><?php if($edit): ?><a class="btn secondary" href="resultados.php">Cancelar</a><?php endif; ?></form>
<table><tr><th>ID</th><th>Votación</th><th>Mesa</th><th>Candidato</th><th>Partido</th><th>Votos</th><th>Usuario</th><th>Fecha</th><th>Acciones</th></tr><?php foreach($rows as $r): ?><tr><td><?=e($r['id_resultado'])?></td><td><?=e($r['votacion'])?></td><td><?=e($r['numero_mesa'])?></td><td><?=e($r['candidato'])?></td><td><?=e($r['partido'])?></td><td><strong><?=e($r['votos'])?></strong></td><td><?=e($r['usuario'])?></td><td><?=e($r['fecha_registro'])?></td><td class="actions"><a class="btn small" href="resultados.php?editar=<?=e($r['id_resultado'])?>">Editar</a><a class="btn small danger" onclick="return confirm('¿Eliminar resultado?')" href="resultados.php?eliminar=<?=e($r['id_resultado'])?>">Eliminar</a></td></tr><?php endforeach; ?></table>
<?php require 'footer.php'; ?>
