<?php require 'config.php'; requiereModulo('votaciones');
$edit=null;
if(isset($_GET['eliminar'])){$pdo->prepare('DELETE FROM votaciones WHERE id_votacion=?')->execute([(int)$_GET['eliminar']]);header('Location: votaciones.php?ok=eliminado');exit;}
if(isset($_GET['editar'])){$st=$pdo->prepare('SELECT * FROM votaciones WHERE id_votacion=?');$st->execute([(int)$_GET['editar']]);$edit=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){$id=(int)($_POST['id_votacion']??0); if($id){$st=$pdo->prepare('UPDATE votaciones SET nombre=?, descripcion=?, fecha_inicio=?, fecha_fin=?, estado=? WHERE id_votacion=?');$st->execute([$_POST['nombre'],$_POST['descripcion'],$_POST['fecha_inicio'],$_POST['fecha_fin'],$_POST['estado'],$id]);}else{$st=$pdo->prepare('INSERT INTO votaciones(nombre,descripcion,fecha_inicio,fecha_fin,estado) VALUES(?,?,?,?,?)');$st->execute([$_POST['nombre'],$_POST['descripcion'],$_POST['fecha_inicio'],$_POST['fecha_fin'],$_POST['estado']]);} header('Location: votaciones.php?ok=guardado');exit;}
require 'header.php'; $rows=$pdo->query('SELECT * FROM votaciones ORDER BY id_votacion DESC')->fetchAll(); ?>
<h1>Votaciones</h1><?php if(isset($_GET['ok'])): ?><div class="alert success">Operación realizada correctamente.</div><?php endif; ?>
<form method="POST" class="form-grid"><input type="hidden" name="id_votacion" value="<?=e($edit['id_votacion']??'')?>"><input name="nombre" placeholder="Nombre de la votación" value="<?=e($edit['nombre']??'')?>" required><input type="date" name="fecha_inicio" value="<?=e($edit['fecha_inicio']??date('Y-m-d'))?>" required><input type="date" name="fecha_fin" value="<?=e($edit['fecha_fin']??date('Y-m-d'))?>" required><select name="estado"><?php foreach(['Planificada','Activa','Cerrada','Anulada'] as $op): ?><option <?=($edit['estado']??'Planificada')==$op?'selected':''?>><?=$op?></option><?php endforeach; ?></select><textarea name="descripcion" placeholder="Descripción" required><?=e($edit['descripcion']??'')?></textarea><button><?= $edit?'Actualizar':'Guardar' ?> votación</button><?php if($edit): ?><a class="btn secondary" href="votaciones.php">Cancelar</a><?php endif; ?></form>
<table><tr><th>ID</th><th>Nombre</th><th>Descripción</th><th>Inicio</th><th>Fin</th><th>Estado</th><th>Acciones</th></tr><?php foreach($rows as $r): ?><tr><td><?=e($r['id_votacion'])?></td><td><?=e($r['nombre'])?></td><td><?=e($r['descripcion'])?></td><td><?=e($r['fecha_inicio'])?></td><td><?=e($r['fecha_fin'])?></td><td><span class="badge"><?=e($r['estado'])?></span></td><td class="actions"><a class="btn small" href="votaciones.php?editar=<?=e($r['id_votacion'])?>">Editar</a><a class="btn small danger" onclick="return confirm('¿Eliminar votación?')" href="votaciones.php?eliminar=<?=e($r['id_votacion'])?>">Eliminar</a></td></tr><?php endforeach; ?></table>
<?php require 'footer.php'; ?>
